name: 'Install MediaWiki'
description: 'Creates a local MediaWiki installation for running phpunit, phan, etc. on MediaWiki extensions'
inputs:
  branch:
    description: 'Branch of MediaWiki that should be installed, e.g. REL1_31, REL1_35, etc.'
    required: true
  dbname:
    description: 'Name of SQL database, e.g. testwiki'
    required: false
    default: "testwiki"
  dbserver:
    description: 'Hostname/port of SQL server, e.g. 127.0.0.1:3306'
    required: false
    default: "127.0.0.1:3306"
  dbtype:
    description: 'Either mysql or postgresql (default: mysql). Note: both MySQL and MariaDB need the value "mysql" here.'
    required: false
    default: "mysql"
  dbuser:
    description: 'Name of SQL user, e.g. "root".'
    required: false
    default: "root"
  dbpass:
    description: 'Password of SQL user. Default: empty (since this is not a publicly accessible SQL server, but a temporary instance).'
    required: false
    default: ""
  extensions:
    description: 'Space-separated list of additional MediaWiki extensions to install, e.g. "Echo PageForms". Default: "".'
    required: false
    default: ""
  skins:
    description: 'Space-separated list of MediaWiki skins to install, e.g. "MinervaNeue". Default: "".'
    required: false
    default: ""
  extraLocalSettings:
    description: 'Relative path to file that will be appended to LocalSettings.php during the installation. It can contain wfLoadExtension() lines, etc. (this path is relative to the directory where this action is invoked)'
    required: false
    default: ""
  noinstall:
    description: "If set to 1, then install.php won't be called. Useful when you only need to run Phan (which only needs MediaWiki sources, but doesn't require full installation, database, etc.)."
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install MediaWiki
      shell: bash
      env:
        BUILDMW_BRANCH: ${{ inputs.branch }}
        BUILDMW_DBNAME: ${{ inputs.dbname }}
        BUILDMW_DBPASS: ${{ inputs.dbpass }}
        BUILDMW_DBSERVER: ${{ inputs.dbserver }}
        BUILDMW_DBTYPE: ${{ inputs.dbtype }}
        BUILDMW_DBUSER: ${{ inputs.dbuser }}
        BUILDMW_EXTRA_EXTENSIONS: ${{ inputs.extensions }}
        BUILDMW_EXTRA_LOCALSETTINGS: ${{ inputs.extraLocalSettings }}
        BUILDMW_EXTRA_SKINS: ${{ inputs.skins }}
        BUILDMW_NOINSTALL: ${{ inputs.noinstall }}
      run: ${{ github.action_path }}/scripts/install_mediawiki.sh

