name: Test action

on: [push, pull_request, workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-24.04
    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3306:3306
        options: --health-cmd="healthcheck.sh --connect --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
    env:
      branch: REL1_39
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
            php-version: '7.4'
            tools: composer
      - uses: actions/cache@v4
        with:
          path: |
            ~/.composer/cache
            buildcache
          key: buildcache-${{ env.branch }}-${{ hashFiles('**/scripts', '**/action.yml') }}
      - name: Call the "install MediaWiki" action
        uses: ./
        with:
          branch: ${{ env.branch }}

      - name: Try running some maintenance script on the newly installed MediaWiki instance
        run: cd mediawiki && echo '{{CURRENTVERSION}}' | php maintenance/parse.php
